#!/bin/sh -e

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -std=c++14 -o base64.cpp.o -c base64.cpp

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -std=c++14 -o DeviceClient.cpp.o -c DeviceClient.cpp -I/Users/albert/albiasoft/albia.client.cpp/third_parties/rapidjson/include -I/Users/albert/albiasoft/albia.client.cpp/third_parties/RxCpp/Rx/v2/src -I/Users/albert/albiasoft/albia.client.cpp/third_parties/protobuf_generated -I/usr/local/include

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -std=c++14 -Wl,-search_paths_first -Wl,-headerpad_max_install_names base64.cpp.o DeviceClient.cpp.o -o DeviceClient -lcurlpp -lcurl -lsioclient -lprotobuf -L/usr/local/lib

