// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/albia.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto3/albia.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class DeviceRecordMsgDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<DeviceRecordMsg> {
  public:
  double doublevalue_;
  float floatvalue_;
  ::google::protobuf::int32 int32value_;
  ::google::protobuf::int64 int64value_;
  ::google::protobuf::uint32 uint32value_;
  ::google::protobuf::uint64 uint64value_;
  bool boolvalue_;
  ::google::protobuf::internal::ArenaStringPtr stringvalue_;
  ::google::protobuf::internal::ArenaStringPtr bytestringvalue_;
} _DeviceRecordMsg_default_instance_;
class DeviceEventMsgDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<DeviceEventMsg> {
} _DeviceEventMsg_default_instance_;

namespace protobuf_proto3_2falbia_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceRecordMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceRecordMsg, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceRecordMsg, deviceid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceRecordMsg, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceRecordMsg, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceRecordMsg, date_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), doublevalue_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), floatvalue_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), int32value_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), int64value_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), uint32value_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), uint64value_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), boolvalue_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), stringvalue_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_DeviceRecordMsg_default_instance_), bytestringvalue_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceRecordMsg, record_value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceEventMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceEventMsg, action_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceEventMsg, deviceid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceEventMsg, targetdeviceid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceEventMsg, date_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceEventMsg, data_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(DeviceRecordMsg)},
  { 19, -1, sizeof(DeviceEventMsg)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_DeviceRecordMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_DeviceEventMsg_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "proto3/albia.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _DeviceRecordMsg_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _DeviceEventMsg_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::google::protobuf::protobuf_proto3_2ftimestamp_2eproto::InitDefaults();
  _DeviceRecordMsg_default_instance_.DefaultConstruct();
  _DeviceEventMsg_default_instance_.DefaultConstruct();
  _DeviceRecordMsg_default_instance_.get_mutable()->date_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
  _DeviceRecordMsg_default_instance_.doublevalue_ = 0;
  _DeviceRecordMsg_default_instance_.floatvalue_ = 0;
  _DeviceRecordMsg_default_instance_.int32value_ = 0;
  _DeviceRecordMsg_default_instance_.int64value_ = GOOGLE_LONGLONG(0);
  _DeviceRecordMsg_default_instance_.uint32value_ = 0u;
  _DeviceRecordMsg_default_instance_.uint64value_ = GOOGLE_ULONGLONG(0);
  _DeviceRecordMsg_default_instance_.boolvalue_ = false;
  _DeviceRecordMsg_default_instance_.stringvalue_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _DeviceRecordMsg_default_instance_.bytestringvalue_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _DeviceEventMsg_default_instance_.get_mutable()->date_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\022proto3/albia.proto\032\026proto3/timestamp.p"
      "roto\"\327\003\n\017DeviceRecordMsg\022\020\n\010deviceId\030\001 \001"
      "(\r\022\013\n\003key\030\002 \001(\t\022)\n\004type\030\003 \001(\0162\033.DeviceRe"
      "cordMsg.RecordType\022(\n\004date\030\004 \001(\0132\032.googl"
      "e.protobuf.Timestamp\022\025\n\013doubleValue\030\005 \001("
      "\001H\000\022\024\n\nfloatValue\030\006 \001(\002H\000\022\024\n\nint32Value\030"
      "\007 \001(\005H\000\022\024\n\nint64Value\030\010 \001(\003H\000\022\025\n\013uint32V"
      "alue\030\t \001(\rH\000\022\025\n\013uint64Value\030\n \001(\004H\000\022\023\n\tb"
      "oolValue\030\013 \001(\010H\000\022\025\n\013stringValue\030\014 \001(\tH\000\022"
      "\031\n\017byteStringValue\030\r \001(\014H\000\"r\n\nRecordType"
      "\022\n\n\006DOUBLE\020\000\022\t\n\005FLOAT\020\001\022\t\n\005INT32\020\002\022\t\n\005IN"
      "T64\020\003\022\n\n\006UINT32\020\004\022\n\n\006UINT64\020\005\022\010\n\004BOOL\020\006\022"
      "\n\n\006STRING\020\007\022\t\n\005BYTES\020\010B\016\n\014record_value\"\202"
      "\001\n\016DeviceEventMsg\022\016\n\006action\030\001 \001(\t\022\020\n\010dev"
      "iceId\030\002 \001(\r\022\026\n\016targetDeviceId\030\003 \001(\r\022(\n\004d"
      "ate\030\004 \001(\0132\032.google.protobuf.Timestamp\022\014\n"
      "\004data\030\005 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 659);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto3/albia.proto", &protobuf_RegisterTypes);
  ::google::protobuf::protobuf_proto3_2ftimestamp_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_proto3_2falbia_2eproto

const ::google::protobuf::EnumDescriptor* DeviceRecordMsg_RecordType_descriptor() {
  protobuf_proto3_2falbia_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto3_2falbia_2eproto::file_level_enum_descriptors[0];
}
bool DeviceRecordMsg_RecordType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const DeviceRecordMsg_RecordType DeviceRecordMsg::DOUBLE;
const DeviceRecordMsg_RecordType DeviceRecordMsg::FLOAT;
const DeviceRecordMsg_RecordType DeviceRecordMsg::INT32;
const DeviceRecordMsg_RecordType DeviceRecordMsg::INT64;
const DeviceRecordMsg_RecordType DeviceRecordMsg::UINT32;
const DeviceRecordMsg_RecordType DeviceRecordMsg::UINT64;
const DeviceRecordMsg_RecordType DeviceRecordMsg::BOOL;
const DeviceRecordMsg_RecordType DeviceRecordMsg::STRING;
const DeviceRecordMsg_RecordType DeviceRecordMsg::BYTES;
const DeviceRecordMsg_RecordType DeviceRecordMsg::RecordType_MIN;
const DeviceRecordMsg_RecordType DeviceRecordMsg::RecordType_MAX;
const int DeviceRecordMsg::RecordType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DeviceRecordMsg::kDeviceIdFieldNumber;
const int DeviceRecordMsg::kKeyFieldNumber;
const int DeviceRecordMsg::kTypeFieldNumber;
const int DeviceRecordMsg::kDateFieldNumber;
const int DeviceRecordMsg::kDoubleValueFieldNumber;
const int DeviceRecordMsg::kFloatValueFieldNumber;
const int DeviceRecordMsg::kInt32ValueFieldNumber;
const int DeviceRecordMsg::kInt64ValueFieldNumber;
const int DeviceRecordMsg::kUint32ValueFieldNumber;
const int DeviceRecordMsg::kUint64ValueFieldNumber;
const int DeviceRecordMsg::kBoolValueFieldNumber;
const int DeviceRecordMsg::kStringValueFieldNumber;
const int DeviceRecordMsg::kByteStringValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeviceRecordMsg::DeviceRecordMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto3_2falbia_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:DeviceRecordMsg)
}
DeviceRecordMsg::DeviceRecordMsg(const DeviceRecordMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.has_date()) {
    date_ = new ::google::protobuf::Timestamp(*from.date_);
  } else {
    date_ = NULL;
  }
  ::memcpy(&deviceid_, &from.deviceid_,
    reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&deviceid_) + sizeof(type_));
  clear_has_record_value();
  switch (from.record_value_case()) {
    case kDoubleValue: {
      set_doublevalue(from.doublevalue());
      break;
    }
    case kFloatValue: {
      set_floatvalue(from.floatvalue());
      break;
    }
    case kInt32Value: {
      set_int32value(from.int32value());
      break;
    }
    case kInt64Value: {
      set_int64value(from.int64value());
      break;
    }
    case kUint32Value: {
      set_uint32value(from.uint32value());
      break;
    }
    case kUint64Value: {
      set_uint64value(from.uint64value());
      break;
    }
    case kBoolValue: {
      set_boolvalue(from.boolvalue());
      break;
    }
    case kStringValue: {
      set_stringvalue(from.stringvalue());
      break;
    }
    case kByteStringValue: {
      set_bytestringvalue(from.bytestringvalue());
      break;
    }
    case RECORD_VALUE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:DeviceRecordMsg)
}

void DeviceRecordMsg::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&date_, 0, reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&date_) + sizeof(type_));
  clear_has_record_value();
  _cached_size_ = 0;
}

DeviceRecordMsg::~DeviceRecordMsg() {
  // @@protoc_insertion_point(destructor:DeviceRecordMsg)
  SharedDtor();
}

void DeviceRecordMsg::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete date_;
  }
  if (has_record_value()) {
    clear_record_value();
  }
}

void DeviceRecordMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DeviceRecordMsg::descriptor() {
  protobuf_proto3_2falbia_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto3_2falbia_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DeviceRecordMsg& DeviceRecordMsg::default_instance() {
  protobuf_proto3_2falbia_2eproto::InitDefaults();
  return *internal_default_instance();
}

DeviceRecordMsg* DeviceRecordMsg::New(::google::protobuf::Arena* arena) const {
  DeviceRecordMsg* n = new DeviceRecordMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DeviceRecordMsg::clear_record_value() {
// @@protoc_insertion_point(one_of_clear_start:DeviceRecordMsg)
  switch (record_value_case()) {
    case kDoubleValue: {
      // No need to clear
      break;
    }
    case kFloatValue: {
      // No need to clear
      break;
    }
    case kInt32Value: {
      // No need to clear
      break;
    }
    case kInt64Value: {
      // No need to clear
      break;
    }
    case kUint32Value: {
      // No need to clear
      break;
    }
    case kUint64Value: {
      // No need to clear
      break;
    }
    case kBoolValue: {
      // No need to clear
      break;
    }
    case kStringValue: {
      record_value_.stringvalue_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kByteStringValue: {
      record_value_.bytestringvalue_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case RECORD_VALUE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = RECORD_VALUE_NOT_SET;
}


void DeviceRecordMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:DeviceRecordMsg)
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && date_ != NULL) {
    delete date_;
  }
  date_ = NULL;
  ::memset(&deviceid_, 0, reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&deviceid_) + sizeof(type_));
  clear_record_value();
}

bool DeviceRecordMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DeviceRecordMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 deviceId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &deviceid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DeviceRecordMsg.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DeviceRecordMsg.RecordType type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::DeviceRecordMsg_RecordType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp date = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_date()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double doubleValue = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u)) {
          clear_record_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &record_value_.doublevalue_)));
          set_has_doublevalue();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float floatValue = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u)) {
          clear_record_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &record_value_.floatvalue_)));
          set_has_floatvalue();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 int32Value = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u)) {
          clear_record_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &record_value_.int32value_)));
          set_has_int32value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 int64Value = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u)) {
          clear_record_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &record_value_.int64value_)));
          set_has_int64value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 uint32Value = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u)) {
          clear_record_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &record_value_.uint32value_)));
          set_has_uint32value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 uint64Value = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u)) {
          clear_record_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &record_value_.uint64value_)));
          set_has_uint64value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool boolValue = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u)) {
          clear_record_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &record_value_.boolvalue_)));
          set_has_boolvalue();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stringValue = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringvalue()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stringvalue().data(), this->stringvalue().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DeviceRecordMsg.stringValue"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes byteStringValue = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bytestringvalue()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DeviceRecordMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DeviceRecordMsg)
  return false;
#undef DO_
}

void DeviceRecordMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DeviceRecordMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 deviceId = 1;
  if (this->deviceid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->deviceid(), output);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeviceRecordMsg.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->key(), output);
  }

  // .DeviceRecordMsg.RecordType type = 3;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->type(), output);
  }

  // .google.protobuf.Timestamp date = 4;
  if (this->has_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->date_, output);
  }

  // double doubleValue = 5;
  if (has_doublevalue()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->doublevalue(), output);
  }

  // float floatValue = 6;
  if (has_floatvalue()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->floatvalue(), output);
  }

  // int32 int32Value = 7;
  if (has_int32value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->int32value(), output);
  }

  // int64 int64Value = 8;
  if (has_int64value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->int64value(), output);
  }

  // uint32 uint32Value = 9;
  if (has_uint32value()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->uint32value(), output);
  }

  // uint64 uint64Value = 10;
  if (has_uint64value()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(10, this->uint64value(), output);
  }

  // bool boolValue = 11;
  if (has_boolvalue()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->boolvalue(), output);
  }

  // string stringValue = 12;
  if (has_stringvalue()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringvalue().data(), this->stringvalue().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeviceRecordMsg.stringValue");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->stringvalue(), output);
  }

  // bytes byteStringValue = 13;
  if (has_bytestringvalue()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      13, this->bytestringvalue(), output);
  }

  // @@protoc_insertion_point(serialize_end:DeviceRecordMsg)
}

::google::protobuf::uint8* DeviceRecordMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DeviceRecordMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 deviceId = 1;
  if (this->deviceid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->deviceid(), target);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeviceRecordMsg.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->key(), target);
  }

  // .DeviceRecordMsg.RecordType type = 3;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->type(), target);
  }

  // .google.protobuf.Timestamp date = 4;
  if (this->has_date()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->date_, deterministic, target);
  }

  // double doubleValue = 5;
  if (has_doublevalue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->doublevalue(), target);
  }

  // float floatValue = 6;
  if (has_floatvalue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->floatvalue(), target);
  }

  // int32 int32Value = 7;
  if (has_int32value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->int32value(), target);
  }

  // int64 int64Value = 8;
  if (has_int64value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->int64value(), target);
  }

  // uint32 uint32Value = 9;
  if (has_uint32value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->uint32value(), target);
  }

  // uint64 uint64Value = 10;
  if (has_uint64value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(10, this->uint64value(), target);
  }

  // bool boolValue = 11;
  if (has_boolvalue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(11, this->boolvalue(), target);
  }

  // string stringValue = 12;
  if (has_stringvalue()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringvalue().data(), this->stringvalue().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeviceRecordMsg.stringValue");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->stringvalue(), target);
  }

  // bytes byteStringValue = 13;
  if (has_bytestringvalue()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        13, this->bytestringvalue(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DeviceRecordMsg)
  return target;
}

size_t DeviceRecordMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DeviceRecordMsg)
  size_t total_size = 0;

  // string key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // .google.protobuf.Timestamp date = 4;
  if (this->has_date()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->date_);
  }

  // uint32 deviceId = 1;
  if (this->deviceid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->deviceid());
  }

  // .DeviceRecordMsg.RecordType type = 3;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  switch (record_value_case()) {
    // double doubleValue = 5;
    case kDoubleValue: {
      total_size += 1 + 8;
      break;
    }
    // float floatValue = 6;
    case kFloatValue: {
      total_size += 1 + 4;
      break;
    }
    // int32 int32Value = 7;
    case kInt32Value: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->int32value());
      break;
    }
    // int64 int64Value = 8;
    case kInt64Value: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->int64value());
      break;
    }
    // uint32 uint32Value = 9;
    case kUint32Value: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->uint32value());
      break;
    }
    // uint64 uint64Value = 10;
    case kUint64Value: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->uint64value());
      break;
    }
    // bool boolValue = 11;
    case kBoolValue: {
      total_size += 1 + 1;
      break;
    }
    // string stringValue = 12;
    case kStringValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->stringvalue());
      break;
    }
    // bytes byteStringValue = 13;
    case kByteStringValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->bytestringvalue());
      break;
    }
    case RECORD_VALUE_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DeviceRecordMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DeviceRecordMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const DeviceRecordMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DeviceRecordMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DeviceRecordMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DeviceRecordMsg)
    MergeFrom(*source);
  }
}

void DeviceRecordMsg::MergeFrom(const DeviceRecordMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DeviceRecordMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.has_date()) {
    mutable_date()->::google::protobuf::Timestamp::MergeFrom(from.date());
  }
  if (from.deviceid() != 0) {
    set_deviceid(from.deviceid());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  switch (from.record_value_case()) {
    case kDoubleValue: {
      set_doublevalue(from.doublevalue());
      break;
    }
    case kFloatValue: {
      set_floatvalue(from.floatvalue());
      break;
    }
    case kInt32Value: {
      set_int32value(from.int32value());
      break;
    }
    case kInt64Value: {
      set_int64value(from.int64value());
      break;
    }
    case kUint32Value: {
      set_uint32value(from.uint32value());
      break;
    }
    case kUint64Value: {
      set_uint64value(from.uint64value());
      break;
    }
    case kBoolValue: {
      set_boolvalue(from.boolvalue());
      break;
    }
    case kStringValue: {
      set_stringvalue(from.stringvalue());
      break;
    }
    case kByteStringValue: {
      set_bytestringvalue(from.bytestringvalue());
      break;
    }
    case RECORD_VALUE_NOT_SET: {
      break;
    }
  }
}

void DeviceRecordMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DeviceRecordMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeviceRecordMsg::CopyFrom(const DeviceRecordMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DeviceRecordMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeviceRecordMsg::IsInitialized() const {
  return true;
}

void DeviceRecordMsg::Swap(DeviceRecordMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeviceRecordMsg::InternalSwap(DeviceRecordMsg* other) {
  key_.Swap(&other->key_);
  std::swap(date_, other->date_);
  std::swap(deviceid_, other->deviceid_);
  std::swap(type_, other->type_);
  std::swap(record_value_, other->record_value_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DeviceRecordMsg::GetMetadata() const {
  protobuf_proto3_2falbia_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto3_2falbia_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DeviceRecordMsg

// uint32 deviceId = 1;
void DeviceRecordMsg::clear_deviceid() {
  deviceid_ = 0u;
}
::google::protobuf::uint32 DeviceRecordMsg::deviceid() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.deviceId)
  return deviceid_;
}
void DeviceRecordMsg::set_deviceid(::google::protobuf::uint32 value) {
  
  deviceid_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.deviceId)
}

// string key = 2;
void DeviceRecordMsg::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DeviceRecordMsg::key() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.key)
  return key_.GetNoArena();
}
void DeviceRecordMsg::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.key)
}
#if LANG_CXX11
void DeviceRecordMsg::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DeviceRecordMsg.key)
}
#endif
void DeviceRecordMsg::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeviceRecordMsg.key)
}
void DeviceRecordMsg::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeviceRecordMsg.key)
}
::std::string* DeviceRecordMsg::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:DeviceRecordMsg.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DeviceRecordMsg::release_key() {
  // @@protoc_insertion_point(field_release:DeviceRecordMsg.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DeviceRecordMsg::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:DeviceRecordMsg.key)
}

// .DeviceRecordMsg.RecordType type = 3;
void DeviceRecordMsg::clear_type() {
  type_ = 0;
}
::DeviceRecordMsg_RecordType DeviceRecordMsg::type() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.type)
  return static_cast< ::DeviceRecordMsg_RecordType >(type_);
}
void DeviceRecordMsg::set_type(::DeviceRecordMsg_RecordType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.type)
}

// .google.protobuf.Timestamp date = 4;
bool DeviceRecordMsg::has_date() const {
  return this != internal_default_instance() && date_ != NULL;
}
void DeviceRecordMsg::clear_date() {
  if (GetArenaNoVirtual() == NULL && date_ != NULL) delete date_;
  date_ = NULL;
}
const ::google::protobuf::Timestamp& DeviceRecordMsg::date() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.date)
  return date_ != NULL ? *date_
                         : *::google::protobuf::Timestamp::internal_default_instance();
}
::google::protobuf::Timestamp* DeviceRecordMsg::mutable_date() {
  
  if (date_ == NULL) {
    date_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:DeviceRecordMsg.date)
  return date_;
}
::google::protobuf::Timestamp* DeviceRecordMsg::release_date() {
  // @@protoc_insertion_point(field_release:DeviceRecordMsg.date)
  
  ::google::protobuf::Timestamp* temp = date_;
  date_ = NULL;
  return temp;
}
void DeviceRecordMsg::set_allocated_date(::google::protobuf::Timestamp* date) {
  delete date_;
  if (date != NULL && date->GetArena() != NULL) {
    ::google::protobuf::Timestamp* new_date = new ::google::protobuf::Timestamp;
    new_date->CopyFrom(*date);
    date = new_date;
  }
  date_ = date;
  if (date) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DeviceRecordMsg.date)
}

// double doubleValue = 5;
bool DeviceRecordMsg::has_doublevalue() const {
  return record_value_case() == kDoubleValue;
}
void DeviceRecordMsg::set_has_doublevalue() {
  _oneof_case_[0] = kDoubleValue;
}
void DeviceRecordMsg::clear_doublevalue() {
  if (has_doublevalue()) {
    record_value_.doublevalue_ = 0;
    clear_has_record_value();
  }
}
double DeviceRecordMsg::doublevalue() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.doubleValue)
  if (has_doublevalue()) {
    return record_value_.doublevalue_;
  }
  return 0;
}
void DeviceRecordMsg::set_doublevalue(double value) {
  if (!has_doublevalue()) {
    clear_record_value();
    set_has_doublevalue();
  }
  record_value_.doublevalue_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.doubleValue)
}

// float floatValue = 6;
bool DeviceRecordMsg::has_floatvalue() const {
  return record_value_case() == kFloatValue;
}
void DeviceRecordMsg::set_has_floatvalue() {
  _oneof_case_[0] = kFloatValue;
}
void DeviceRecordMsg::clear_floatvalue() {
  if (has_floatvalue()) {
    record_value_.floatvalue_ = 0;
    clear_has_record_value();
  }
}
float DeviceRecordMsg::floatvalue() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.floatValue)
  if (has_floatvalue()) {
    return record_value_.floatvalue_;
  }
  return 0;
}
void DeviceRecordMsg::set_floatvalue(float value) {
  if (!has_floatvalue()) {
    clear_record_value();
    set_has_floatvalue();
  }
  record_value_.floatvalue_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.floatValue)
}

// int32 int32Value = 7;
bool DeviceRecordMsg::has_int32value() const {
  return record_value_case() == kInt32Value;
}
void DeviceRecordMsg::set_has_int32value() {
  _oneof_case_[0] = kInt32Value;
}
void DeviceRecordMsg::clear_int32value() {
  if (has_int32value()) {
    record_value_.int32value_ = 0;
    clear_has_record_value();
  }
}
::google::protobuf::int32 DeviceRecordMsg::int32value() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.int32Value)
  if (has_int32value()) {
    return record_value_.int32value_;
  }
  return 0;
}
void DeviceRecordMsg::set_int32value(::google::protobuf::int32 value) {
  if (!has_int32value()) {
    clear_record_value();
    set_has_int32value();
  }
  record_value_.int32value_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.int32Value)
}

// int64 int64Value = 8;
bool DeviceRecordMsg::has_int64value() const {
  return record_value_case() == kInt64Value;
}
void DeviceRecordMsg::set_has_int64value() {
  _oneof_case_[0] = kInt64Value;
}
void DeviceRecordMsg::clear_int64value() {
  if (has_int64value()) {
    record_value_.int64value_ = GOOGLE_LONGLONG(0);
    clear_has_record_value();
  }
}
::google::protobuf::int64 DeviceRecordMsg::int64value() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.int64Value)
  if (has_int64value()) {
    return record_value_.int64value_;
  }
  return GOOGLE_LONGLONG(0);
}
void DeviceRecordMsg::set_int64value(::google::protobuf::int64 value) {
  if (!has_int64value()) {
    clear_record_value();
    set_has_int64value();
  }
  record_value_.int64value_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.int64Value)
}

// uint32 uint32Value = 9;
bool DeviceRecordMsg::has_uint32value() const {
  return record_value_case() == kUint32Value;
}
void DeviceRecordMsg::set_has_uint32value() {
  _oneof_case_[0] = kUint32Value;
}
void DeviceRecordMsg::clear_uint32value() {
  if (has_uint32value()) {
    record_value_.uint32value_ = 0u;
    clear_has_record_value();
  }
}
::google::protobuf::uint32 DeviceRecordMsg::uint32value() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.uint32Value)
  if (has_uint32value()) {
    return record_value_.uint32value_;
  }
  return 0u;
}
void DeviceRecordMsg::set_uint32value(::google::protobuf::uint32 value) {
  if (!has_uint32value()) {
    clear_record_value();
    set_has_uint32value();
  }
  record_value_.uint32value_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.uint32Value)
}

// uint64 uint64Value = 10;
bool DeviceRecordMsg::has_uint64value() const {
  return record_value_case() == kUint64Value;
}
void DeviceRecordMsg::set_has_uint64value() {
  _oneof_case_[0] = kUint64Value;
}
void DeviceRecordMsg::clear_uint64value() {
  if (has_uint64value()) {
    record_value_.uint64value_ = GOOGLE_ULONGLONG(0);
    clear_has_record_value();
  }
}
::google::protobuf::uint64 DeviceRecordMsg::uint64value() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.uint64Value)
  if (has_uint64value()) {
    return record_value_.uint64value_;
  }
  return GOOGLE_ULONGLONG(0);
}
void DeviceRecordMsg::set_uint64value(::google::protobuf::uint64 value) {
  if (!has_uint64value()) {
    clear_record_value();
    set_has_uint64value();
  }
  record_value_.uint64value_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.uint64Value)
}

// bool boolValue = 11;
bool DeviceRecordMsg::has_boolvalue() const {
  return record_value_case() == kBoolValue;
}
void DeviceRecordMsg::set_has_boolvalue() {
  _oneof_case_[0] = kBoolValue;
}
void DeviceRecordMsg::clear_boolvalue() {
  if (has_boolvalue()) {
    record_value_.boolvalue_ = false;
    clear_has_record_value();
  }
}
bool DeviceRecordMsg::boolvalue() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.boolValue)
  if (has_boolvalue()) {
    return record_value_.boolvalue_;
  }
  return false;
}
void DeviceRecordMsg::set_boolvalue(bool value) {
  if (!has_boolvalue()) {
    clear_record_value();
    set_has_boolvalue();
  }
  record_value_.boolvalue_ = value;
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.boolValue)
}

// string stringValue = 12;
bool DeviceRecordMsg::has_stringvalue() const {
  return record_value_case() == kStringValue;
}
void DeviceRecordMsg::set_has_stringvalue() {
  _oneof_case_[0] = kStringValue;
}
void DeviceRecordMsg::clear_stringvalue() {
  if (has_stringvalue()) {
    record_value_.stringvalue_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_record_value();
  }
}
const ::std::string& DeviceRecordMsg::stringvalue() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.stringValue)
  if (has_stringvalue()) {
    return record_value_.stringvalue_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
void DeviceRecordMsg::set_stringvalue(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.stringValue)
  if (!has_stringvalue()) {
    clear_record_value();
    set_has_stringvalue();
    record_value_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  record_value_.stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.stringValue)
}
#if LANG_CXX11
void DeviceRecordMsg::set_stringvalue(::std::string&& value) {
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.stringValue)
  if (!has_stringvalue()) {
    clear_record_value();
    set_has_stringvalue();
    record_value_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  record_value_.stringvalue_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DeviceRecordMsg.stringValue)
}
#endif
void DeviceRecordMsg::set_stringvalue(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_stringvalue()) {
    clear_record_value();
    set_has_stringvalue();
    record_value_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  record_value_.stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeviceRecordMsg.stringValue)
}
void DeviceRecordMsg::set_stringvalue(const char* value, size_t size) {
  if (!has_stringvalue()) {
    clear_record_value();
    set_has_stringvalue();
    record_value_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  record_value_.stringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeviceRecordMsg.stringValue)
}
::std::string* DeviceRecordMsg::mutable_stringvalue() {
  if (!has_stringvalue()) {
    clear_record_value();
    set_has_stringvalue();
    record_value_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:DeviceRecordMsg.stringValue)
  return record_value_.stringvalue_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DeviceRecordMsg::release_stringvalue() {
  // @@protoc_insertion_point(field_release:DeviceRecordMsg.stringValue)
  if (has_stringvalue()) {
    clear_has_record_value();
    return record_value_.stringvalue_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
void DeviceRecordMsg::set_allocated_stringvalue(::std::string* stringvalue) {
  if (!has_stringvalue()) {
    record_value_.stringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_record_value();
  if (stringvalue != NULL) {
    set_has_stringvalue();
    record_value_.stringvalue_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        stringvalue);
  }
  // @@protoc_insertion_point(field_set_allocated:DeviceRecordMsg.stringValue)
}

// bytes byteStringValue = 13;
bool DeviceRecordMsg::has_bytestringvalue() const {
  return record_value_case() == kByteStringValue;
}
void DeviceRecordMsg::set_has_bytestringvalue() {
  _oneof_case_[0] = kByteStringValue;
}
void DeviceRecordMsg::clear_bytestringvalue() {
  if (has_bytestringvalue()) {
    record_value_.bytestringvalue_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_record_value();
  }
}
const ::std::string& DeviceRecordMsg::bytestringvalue() const {
  // @@protoc_insertion_point(field_get:DeviceRecordMsg.byteStringValue)
  if (has_bytestringvalue()) {
    return record_value_.bytestringvalue_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
void DeviceRecordMsg::set_bytestringvalue(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.byteStringValue)
  if (!has_bytestringvalue()) {
    clear_record_value();
    set_has_bytestringvalue();
    record_value_.bytestringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  record_value_.bytestringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.byteStringValue)
}
#if LANG_CXX11
void DeviceRecordMsg::set_bytestringvalue(::std::string&& value) {
  // @@protoc_insertion_point(field_set:DeviceRecordMsg.byteStringValue)
  if (!has_bytestringvalue()) {
    clear_record_value();
    set_has_bytestringvalue();
    record_value_.bytestringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  record_value_.bytestringvalue_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DeviceRecordMsg.byteStringValue)
}
#endif
void DeviceRecordMsg::set_bytestringvalue(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_bytestringvalue()) {
    clear_record_value();
    set_has_bytestringvalue();
    record_value_.bytestringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  record_value_.bytestringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeviceRecordMsg.byteStringValue)
}
void DeviceRecordMsg::set_bytestringvalue(const void* value, size_t size) {
  if (!has_bytestringvalue()) {
    clear_record_value();
    set_has_bytestringvalue();
    record_value_.bytestringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  record_value_.bytestringvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeviceRecordMsg.byteStringValue)
}
::std::string* DeviceRecordMsg::mutable_bytestringvalue() {
  if (!has_bytestringvalue()) {
    clear_record_value();
    set_has_bytestringvalue();
    record_value_.bytestringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:DeviceRecordMsg.byteStringValue)
  return record_value_.bytestringvalue_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DeviceRecordMsg::release_bytestringvalue() {
  // @@protoc_insertion_point(field_release:DeviceRecordMsg.byteStringValue)
  if (has_bytestringvalue()) {
    clear_has_record_value();
    return record_value_.bytestringvalue_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
void DeviceRecordMsg::set_allocated_bytestringvalue(::std::string* bytestringvalue) {
  if (!has_bytestringvalue()) {
    record_value_.bytestringvalue_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_record_value();
  if (bytestringvalue != NULL) {
    set_has_bytestringvalue();
    record_value_.bytestringvalue_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        bytestringvalue);
  }
  // @@protoc_insertion_point(field_set_allocated:DeviceRecordMsg.byteStringValue)
}

bool DeviceRecordMsg::has_record_value() const {
  return record_value_case() != RECORD_VALUE_NOT_SET;
}
void DeviceRecordMsg::clear_has_record_value() {
  _oneof_case_[0] = RECORD_VALUE_NOT_SET;
}
DeviceRecordMsg::RecordValueCase DeviceRecordMsg::record_value_case() const {
  return DeviceRecordMsg::RecordValueCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DeviceEventMsg::kActionFieldNumber;
const int DeviceEventMsg::kDeviceIdFieldNumber;
const int DeviceEventMsg::kTargetDeviceIdFieldNumber;
const int DeviceEventMsg::kDateFieldNumber;
const int DeviceEventMsg::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeviceEventMsg::DeviceEventMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto3_2falbia_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:DeviceEventMsg)
}
DeviceEventMsg::DeviceEventMsg(const DeviceEventMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  action_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.action().size() > 0) {
    action_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.action_);
  }
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.has_date()) {
    date_ = new ::google::protobuf::Timestamp(*from.date_);
  } else {
    date_ = NULL;
  }
  ::memcpy(&deviceid_, &from.deviceid_,
    reinterpret_cast<char*>(&targetdeviceid_) -
    reinterpret_cast<char*>(&deviceid_) + sizeof(targetdeviceid_));
  // @@protoc_insertion_point(copy_constructor:DeviceEventMsg)
}

void DeviceEventMsg::SharedCtor() {
  action_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&date_, 0, reinterpret_cast<char*>(&targetdeviceid_) -
    reinterpret_cast<char*>(&date_) + sizeof(targetdeviceid_));
  _cached_size_ = 0;
}

DeviceEventMsg::~DeviceEventMsg() {
  // @@protoc_insertion_point(destructor:DeviceEventMsg)
  SharedDtor();
}

void DeviceEventMsg::SharedDtor() {
  action_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete date_;
  }
}

void DeviceEventMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DeviceEventMsg::descriptor() {
  protobuf_proto3_2falbia_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto3_2falbia_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DeviceEventMsg& DeviceEventMsg::default_instance() {
  protobuf_proto3_2falbia_2eproto::InitDefaults();
  return *internal_default_instance();
}

DeviceEventMsg* DeviceEventMsg::New(::google::protobuf::Arena* arena) const {
  DeviceEventMsg* n = new DeviceEventMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DeviceEventMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:DeviceEventMsg)
  action_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && date_ != NULL) {
    delete date_;
  }
  date_ = NULL;
  ::memset(&deviceid_, 0, reinterpret_cast<char*>(&targetdeviceid_) -
    reinterpret_cast<char*>(&deviceid_) + sizeof(targetdeviceid_));
}

bool DeviceEventMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DeviceEventMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string action = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_action()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->action().data(), this->action().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DeviceEventMsg.action"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 deviceId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &deviceid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 targetDeviceId = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &targetdeviceid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp date = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_date()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string data = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_data()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->data().data(), this->data().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DeviceEventMsg.data"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DeviceEventMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DeviceEventMsg)
  return false;
#undef DO_
}

void DeviceEventMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DeviceEventMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string action = 1;
  if (this->action().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->action().data(), this->action().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeviceEventMsg.action");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->action(), output);
  }

  // uint32 deviceId = 2;
  if (this->deviceid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->deviceid(), output);
  }

  // uint32 targetDeviceId = 3;
  if (this->targetdeviceid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->targetdeviceid(), output);
  }

  // .google.protobuf.Timestamp date = 4;
  if (this->has_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->date_, output);
  }

  // string data = 5;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeviceEventMsg.data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->data(), output);
  }

  // @@protoc_insertion_point(serialize_end:DeviceEventMsg)
}

::google::protobuf::uint8* DeviceEventMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DeviceEventMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string action = 1;
  if (this->action().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->action().data(), this->action().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeviceEventMsg.action");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->action(), target);
  }

  // uint32 deviceId = 2;
  if (this->deviceid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->deviceid(), target);
  }

  // uint32 targetDeviceId = 3;
  if (this->targetdeviceid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->targetdeviceid(), target);
  }

  // .google.protobuf.Timestamp date = 4;
  if (this->has_date()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->date_, deterministic, target);
  }

  // string data = 5;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DeviceEventMsg.data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DeviceEventMsg)
  return target;
}

size_t DeviceEventMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DeviceEventMsg)
  size_t total_size = 0;

  // string action = 1;
  if (this->action().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->action());
  }

  // string data = 5;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->data());
  }

  // .google.protobuf.Timestamp date = 4;
  if (this->has_date()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->date_);
  }

  // uint32 deviceId = 2;
  if (this->deviceid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->deviceid());
  }

  // uint32 targetDeviceId = 3;
  if (this->targetdeviceid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->targetdeviceid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DeviceEventMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DeviceEventMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const DeviceEventMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DeviceEventMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DeviceEventMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DeviceEventMsg)
    MergeFrom(*source);
  }
}

void DeviceEventMsg::MergeFrom(const DeviceEventMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DeviceEventMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.action().size() > 0) {

    action_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.action_);
  }
  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.has_date()) {
    mutable_date()->::google::protobuf::Timestamp::MergeFrom(from.date());
  }
  if (from.deviceid() != 0) {
    set_deviceid(from.deviceid());
  }
  if (from.targetdeviceid() != 0) {
    set_targetdeviceid(from.targetdeviceid());
  }
}

void DeviceEventMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DeviceEventMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeviceEventMsg::CopyFrom(const DeviceEventMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DeviceEventMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeviceEventMsg::IsInitialized() const {
  return true;
}

void DeviceEventMsg::Swap(DeviceEventMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeviceEventMsg::InternalSwap(DeviceEventMsg* other) {
  action_.Swap(&other->action_);
  data_.Swap(&other->data_);
  std::swap(date_, other->date_);
  std::swap(deviceid_, other->deviceid_);
  std::swap(targetdeviceid_, other->targetdeviceid_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DeviceEventMsg::GetMetadata() const {
  protobuf_proto3_2falbia_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto3_2falbia_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DeviceEventMsg

// string action = 1;
void DeviceEventMsg::clear_action() {
  action_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DeviceEventMsg::action() const {
  // @@protoc_insertion_point(field_get:DeviceEventMsg.action)
  return action_.GetNoArena();
}
void DeviceEventMsg::set_action(const ::std::string& value) {
  
  action_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeviceEventMsg.action)
}
#if LANG_CXX11
void DeviceEventMsg::set_action(::std::string&& value) {
  
  action_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DeviceEventMsg.action)
}
#endif
void DeviceEventMsg::set_action(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  action_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeviceEventMsg.action)
}
void DeviceEventMsg::set_action(const char* value, size_t size) {
  
  action_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeviceEventMsg.action)
}
::std::string* DeviceEventMsg::mutable_action() {
  
  // @@protoc_insertion_point(field_mutable:DeviceEventMsg.action)
  return action_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DeviceEventMsg::release_action() {
  // @@protoc_insertion_point(field_release:DeviceEventMsg.action)
  
  return action_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DeviceEventMsg::set_allocated_action(::std::string* action) {
  if (action != NULL) {
    
  } else {
    
  }
  action_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), action);
  // @@protoc_insertion_point(field_set_allocated:DeviceEventMsg.action)
}

// uint32 deviceId = 2;
void DeviceEventMsg::clear_deviceid() {
  deviceid_ = 0u;
}
::google::protobuf::uint32 DeviceEventMsg::deviceid() const {
  // @@protoc_insertion_point(field_get:DeviceEventMsg.deviceId)
  return deviceid_;
}
void DeviceEventMsg::set_deviceid(::google::protobuf::uint32 value) {
  
  deviceid_ = value;
  // @@protoc_insertion_point(field_set:DeviceEventMsg.deviceId)
}

// uint32 targetDeviceId = 3;
void DeviceEventMsg::clear_targetdeviceid() {
  targetdeviceid_ = 0u;
}
::google::protobuf::uint32 DeviceEventMsg::targetdeviceid() const {
  // @@protoc_insertion_point(field_get:DeviceEventMsg.targetDeviceId)
  return targetdeviceid_;
}
void DeviceEventMsg::set_targetdeviceid(::google::protobuf::uint32 value) {
  
  targetdeviceid_ = value;
  // @@protoc_insertion_point(field_set:DeviceEventMsg.targetDeviceId)
}

// .google.protobuf.Timestamp date = 4;
bool DeviceEventMsg::has_date() const {
  return this != internal_default_instance() && date_ != NULL;
}
void DeviceEventMsg::clear_date() {
  if (GetArenaNoVirtual() == NULL && date_ != NULL) delete date_;
  date_ = NULL;
}
const ::google::protobuf::Timestamp& DeviceEventMsg::date() const {
  // @@protoc_insertion_point(field_get:DeviceEventMsg.date)
  return date_ != NULL ? *date_
                         : *::google::protobuf::Timestamp::internal_default_instance();
}
::google::protobuf::Timestamp* DeviceEventMsg::mutable_date() {
  
  if (date_ == NULL) {
    date_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:DeviceEventMsg.date)
  return date_;
}
::google::protobuf::Timestamp* DeviceEventMsg::release_date() {
  // @@protoc_insertion_point(field_release:DeviceEventMsg.date)
  
  ::google::protobuf::Timestamp* temp = date_;
  date_ = NULL;
  return temp;
}
void DeviceEventMsg::set_allocated_date(::google::protobuf::Timestamp* date) {
  delete date_;
  if (date != NULL && date->GetArena() != NULL) {
    ::google::protobuf::Timestamp* new_date = new ::google::protobuf::Timestamp;
    new_date->CopyFrom(*date);
    date = new_date;
  }
  date_ = date;
  if (date) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DeviceEventMsg.date)
}

// string data = 5;
void DeviceEventMsg::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DeviceEventMsg::data() const {
  // @@protoc_insertion_point(field_get:DeviceEventMsg.data)
  return data_.GetNoArena();
}
void DeviceEventMsg::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeviceEventMsg.data)
}
#if LANG_CXX11
void DeviceEventMsg::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DeviceEventMsg.data)
}
#endif
void DeviceEventMsg::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeviceEventMsg.data)
}
void DeviceEventMsg::set_data(const char* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeviceEventMsg.data)
}
::std::string* DeviceEventMsg::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:DeviceEventMsg.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DeviceEventMsg::release_data() {
  // @@protoc_insertion_point(field_release:DeviceEventMsg.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DeviceEventMsg::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:DeviceEventMsg.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
